export const filtreringsValg = [
  'Permittert',
  'Student',
  'Arbeidsledig',
  'Konkurs',
  'SelvstendigNaeringsdrivende',
  'Frilanser',
  'Nydimmitert',
  'Laerling',
  'Doktorgradskandidat',
  'SagtOppSelv',
  'MottarAnnenStotteFraNav',
  'StreikLockout',
  'MottarVentelonn',
].sort();
